// #[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
// pub struct Category {
// 	pub key: String,
// 	pub name: String,
// 	pub description: String,
// 	pub emoji: String,
// }

pub const CATEGORIES: [&str; 38] = [
	"3d_modelling",
	"analytics",
	"application_launcher",
	"artificial_intelligence",
	"boot_loader",
	"browser",
	"browser_extension",
	"cli",
	"code_editor",
	"desktop_environment",
	"development",
	"discussion_forum",
	"document_viewer",
	"documentation_generator",
	"education",
	"email_client",
	"entertainment",
	"file_manager",
	"game",
	"game_development",
	"health_and_fitness",
	"library",
	"music",
	"news_and_journalism",
	"note_taking",
	"notification_daemon",
	"package_registry",
	"photo_and_video",
	"productivity",
	"search_engine",
	"social_networking",
	"syntax_highlighting",
	"system",
	"terminal",
	"translation_tool",
	"userstyle",
	"wiki",
	"window_manager",
];
